public class CollectionDemo {
  public static void ListDemo()
    {
     List<String> nameList = new List<String>();  
        nameList.add('haritha');
        nameList.add('amrutha');
        nameList.add('anil');
        nameList.add('praneeth');
        system.debug('nameList'+nameList); 
        
         set<String> nameset = new set<String>();  
         nameset.add('haritha');
         nameset.add('amrutha');
         nameset.add('anil');
         nameset.add('praneeth');
        system.debug(' nameset'+ nameset); 
        
        
        
    }
}