public class MyFirstClass {
    public list<string>ArrayList{get;set;}
    public MyFirstClass()
    {
        ArrayList=new List<string>();
        Arraylist.add('January');
        Arraylist.add('February');
        Arraylist.add('March');
        Arraylist.add('April');
        Arraylist.add('May');
        Arraylist.add('June');
        Arraylist.add('july');
        Arraylist.add('August');
        Arraylist.add('September');
        Arraylist.add('October');
        Arraylist.add('November');
        Arraylist.add('December');


    }
}